### ISSUE TITLE
Compare the page for nomad_helper_url to the expected nomadhelper.html

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Super.Human.Portal#57]
We also want to compare the page for nomad_helper_url to the expected nomadhelper.html and show a similar warning if they don't match exactly.  Genesis doesn't have access to install nomad_helper.html, so we want to have SuperHumanPortal verify that the nomad_helper.html installed by the administrator matches the copy under `resources/`.

If we are reading nomad_helper_url, then we need to safely handle the case where the URL doesn't resolve properly (because it was not properly configured).  I would expect the administrator to test this, but until it is fixed, Super.Human.Portal should use the default logic instead.

A mismatching nomad_helper.html is not necessarily a blocker, so I think we should attempt to use the helper anyway in this case.  If this fails, it should be handled by the callback logic.

_Originally posted by @JoelProminic in https://github.com/Moonshine-IDE/Super.Human.Portal/issues/54#issuecomment-2088775767_

**Comment by piotrzarzycki21** [comment]
@JoelProminic I was thinking to have that comparision during configuration fetching, where we are retrieving nomad_helper_url. Where do you think it should actually happen if not in that moment ?

**Comment by piotrzarzycki21** [comment]
I'm moving this for the next release. I have started implementing this. Should be ready soon, but let's not hold this since our first target is internal use.

**Comment by JoelProminic** [comment]
I think that running this just after  calling ConfigRead make sense.   You can then load the `nomad_helper_url` and `resources/nomad_helper.html` pages [into memory](https://stackoverflow.com/questions/42138572/how-to-read-html-file-contents-in-javascript) and compare them.

**Comment by piotrzarzycki21** [comment]
I have implemented initial version, but it doesn't work yet as I wanted to so, it's still require a bit more time. I have pushed my changes to branch. I will notify about significant progress and when it will be ready for tests.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I think I have whole comparision of nomadhelper.html ready. I'm using HTTPRequest to load local and remote files. I'm using native JS module called ["crypto"](https://github.com/Moonshine-IDE/Super.Human.Portal/blob/8af10c70da99ddb59c4fc374cc1735fcb3ab4831/Super.Human.Portal_Royale/src/net/apacheRoyaleTemplatedApp/utils/UtilsCore.as#L53) to compute hashes for both files.

Not we should discuss what kind of message we should display to the user.

**Comment by JoelProminic** [comment]
Here is a message based on the [existing Nomad check](https://github.com/Moonshine-IDE/Super.Human.Portal/issues/54#issuecomment-2110781462)

>Nomad Helper does not match the current version of Super.Human.Portal.  To fix this:
> - Copy `%data_directory%/domino/html/Super.Human.Portal/js-release/resources/nomadhelper.html` \[Copy to Cllpboard\] to `/opt/hcl/domino/notes/latest/linux/nomad-files` \[Copy to Cllpboard\] on your Nomad server

This should be displayed once per day per user.

**Comment by piotrzarzycki21** [comment]
@JoelProminic It turns out I have this implemented or rather logic is but nothing on the UI side. However there is one issue: I'm loading nomad_helper.html local one which is part of this app and I'm trying load into memory helper from some configured URL. Which of course turns into CORS issue. I'm wondering how handle this, because this will be always the case SHP trying to load external html file which is not part of SHP domain. 

I have logic which compare

**Comment by JoelProminic** [comment]
Ah, does this match up with the CORS errors from #83?  I didn't get back to that after resolving the main issue in #83.  I'm still a little unclear why this request give a CORS error but the main call does not.

**Comment by JoelProminic** [comment]
I see we had previously cleared the CORS errors with nomad-config.yml
https://github.com/Moonshine-IDE/Super.Human.Portal/issues/53#issuecomment-2030580767

The provisioner details are here:
https://github.com/STARTcloud/hcl_roles/blob/22723b36577a67ff2e0df09260e0b447275fa489/roles/domino_nomadweb/templates/nomad-config.yml.j2#L11
https://github.com/STARTcloud/hcl_roles/blob/22723b36577a67ff2e0df09260e0b447275fa489/roles/domino_nomadweb/tasks/main.yml#L196-L202

I do see nomad-config.yml on my instance, through:

```
domino@nomad-0725:~$ cat nomad-config.yml 
host: '0.0.0.0'
port: "9443"
access_log:
  enabled: true
httpHeaders:
  Access-Control-Allow-Origin: "https://notes.nomad-0725.shi.com"
  Access-Control-Allow-Methods: "GET, POST, OPTIONS"
  Access-Control-Allow-Credentials: "true"
  Content-Security-Policy: "frame-ancestors 'self' https://notes.nomad-0725.shi.com https://domino.nomad-0725.shi.com https://nomad-0725.shi.com"
```

**Comment by piotrzarzycki21** [comment]
@JoelProminic It looks like in my file I have wrong header in the config which is: 

```
cat nomad-config.yml
host: '0.0.0.0'
port: "9443"
access_log:
  enabled: true
httpHeaders:
  Access-Control-Allow-Origin: "https://notes.earth.startcloud.com"
  Access-Control-Allow-Methods: "GET, POST, OPTIONS"
  Access-Control-Allow-Credentials: "true"
  Content-Security-Policy: "frame-ancestors 'self' https://notes.earth.startcloud.com https://domino.earth.startcloud.com https://earth.startcloud.com"
```

But I should probably have this like that, because this is how my server url actually:

```
httpHeaders:
  Access-Control-Allow-Origin: "https://domino.earth.startcloud.com"
  Access-Control-Allow-Methods: "GET, POST, OPTIONS"
  Access-Control-Allow-Credentials: "true"
  Content-Security-Policy: "frame-ancestors 'self' https://notes.earth.startcloud.com https://domino.earth.startcloud.com https://earth.startcloud.com"
```

The thing is that Opening nomadhelper is happen [using iFrame](https://github.com/Moonshine-IDE/Super.Human.Portal/blob/f99aa59eb7ecc6c144c77b5dbc23f19e02528d61/Super.Human.Portal_Royale/src/net/apacheRoyaleTemplatedApp/controller/CommandLaunchNomadLink.as#L59), but in current solution for file comparision I'm trying to [directly load](https://github.com/Moonshine-IDE/Super.Human.Portal/blob/f99aa59eb7ecc6c144c77b5dbc23f19e02528d61/Super.Human.Portal_Royale/src/net/apacheRoyaleTemplatedApp/utils/NomadHelperLoaderTasks.as#L37) ([NomadHelperDelegate](https://github.com/Moonshine-IDE/Super.Human.Portal/blob/f99aa59eb7ecc6c144c77b5dbc23f19e02528d61/Super.Human.Portal_Royale/src/net/apacheRoyaleTemplatedApp/services/NomadHelperDelegate.as#L12)) that file in memory using different method. 

However I'm not sure what would an implication of changing this configuration to that direction for other features. I may try that.
